name: CI_Main_branch
on: 
  pull_request:
    branches:  
    - main
    - master
    
jobs:
  build_environment:
    timeout-minutes: 60
    name: ${{ matrix.os }} - Node.js ${{ matrix.node-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [ 16, 18, 20]       
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: pwd
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: pwReport_${{ matrix.os }}_node${{ matrix.node-version }}
        path: playwright-report/
        retention-days: 30
