name: Playwright Tests
on:
  pull_request:
    branches: [main, master]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [16, 18, 20]
    uses: ./.github/workflows/reusable-tests.yml
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}
      test-command: "npx playwright test"
