name: Push Tests
on:
  push:
    branches-ignore:
      - main
      - master
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    uses: ./.github/workflows/reusable-tests.yml
    with:
      os: ${{ matrix.os }}
      node-version: ${{ matrix.node-version }}
      test-command: "REPNAME=Chrome_ npx playwright test -g \"chromium\""

  notify:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Notify Microsoft Teams
        uses: teknicode/ms-teams-github-action@master # NOTE: This is a public action, make sure you trust it.
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          title: "Push Tests ${{ needs.test.result }}"
          summary: "Push tests have ${{ needs.test.result }}"
          actions: |
            [
              {
                "type": "Action.OpenUrl",
                "title": "View Run",
                "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
              }
            ]
